import type { Metadata } from "next";
import { Oxygen } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import LocoMotiveProvider from "@/providers/locomotive";
import Header from "@/components/header";
import Footer from "@/components/footer";

const fontSans = Oxygen({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-oxygen"
});

export const metadata: Metadata = {
  title: "Begum Inayat",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("font-oxygen", fontSans.variable)}>
        <main className="w-full h-full top-0 inset-0 min-h-screen bg-red-800/50 pointer-events-none z-[9999] fixed"></main>
        <div className="w-full py-12 flex justify-center items-center bg-red-700 text-white sticky top-0 z-[9999]">
          <p className="text-xl font-bold p-4 text-center">
            <strong>Notice:</strong> This website is the intellectual property
            of{" "}
            <a
              href="https://github.com/Zain-ul-din"
              className="underline underline-offset-2"
            >
              Zain ul din
            </a>
            . Full ownership will be transferred to Begum Inayat Welfare Society
            upon receipt of the remaining payment.
          </p>
        </div>
        <Header />
        <LocoMotiveProvider>{children}</LocoMotiveProvider>
        <Footer />
      </body>
    </html>
  );
}
