import type { Metadata } from "next";
import { Oxygen } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const fontSans = Oxygen({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-oxygen",
});

export const metadata: Metadata = {
  title: "Begum Inayat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("font-oxygen", fontSans.variable)}>{children}</body>
    </html>
  );
}
